language: java
branches:
  only:
  - develop
  - "/^release-[0-999].[0-999]$/"
  - master
notifications:
  slack:
    secure: qtceeBvzqL4jaYEcVLUiQOrinYFFro6PrZWHssIQRGGei5mmvXcmueZ9MuMhM+I2dm+56HH95/AJpZ3+8uy0XbSDkGmNW8uJB5SdbH3fRkqOS2OkTcKwiM8oxsnArg2whLJixTyOvFvEcdnraAPjf61ltNHtFQlRxlCAQ9NecXOMZJsatmIfgAk/SHz0gjGhndE5WJCRtL2QUJHWEnxe4Dpf+jahdD2kughrPHgWRtNz6FRZZ3IQMeca7m+1OPeQKZL+MGBpR7UGEj82fAALOAFyIqScG4heXH2aauYOxki3mDsc05ZAGZkLZL+9TjKAwSwlVWW4gRbF+ErplEofOVrrR1v3v5n+HuRykIB5NDtYMfv7BPLjisjsGOrbJdvcvMBRrL/HzNG26fwszAuDAnrCo+LI4AJzKSOuhuVstwg6T6Ldk/RtdGuz9JIIxI8Ql4LSh5RBlq1G2T12Rc0h9v7ljDs9frsvrdjz68zWvie1rVZoGbLy7DSutNTMKwWETCdXSoFUKwX7uxvQOFv09u1IRq3Du33NwVbD22YLvrXvY9r3mhl3RL3Dmft0KJIp+Pitm5WnTybmGu5KwkuFFZzzkeS4ztz9dks06puRe9JN5P6TEkLjQnps2Ql66lT3djmL8F8BcdN/Rttb7VXy3hxjIaJNQP7jroBB1NLL/oY=
  email:
    recipients:
    - n.casanova@alumnos.upm.es
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nataliacasanova
  -Dsonar.login=$SONAR
deploy:
  app: imvg-devops-casanova-natalia
  provider: heroku
  api_key: "$HEROKU"
  on:
    branch: master
